---
title: "Lab 2 - Data wrangling"
author: "Jessica St. Jean"
date: "February 10, 2026"
format: 
  pdf: default # for final output
---

```{r}
#| eval: true
#| message: false

library(tidyverse)
```

# Questions

## Part 1

```{r}
?midwest
```

\newpage

### Question 1

```{r}
midwest |>
count(state, sort = TRUE)
```

Comment: Illinois has the most amount of counties with 102, and Wisconsin has the least with 72.

\newpage

### Question 2

```{r}

midwest |>
  count(county,state) |>
  count(county, name = "n_states")|>
  filter(n_states == n_distinct(midwest$state)) 
  
```

\newpage

### Question 3

```{r}
midwest |>
  filter(popdensity > 25000) |>
  select(county,state,popdensity,poptotal,area) |>
  arrange(desc(popdensity))
```

```{r}
midwest |>
  filter(popdensity == max(popdensity)) |>
  select(county,state,popdensity,poptotal,area)
```

\newpage

### Question 4

```{r}

```

\newpage

### Question 5

\newpage

### Question 6

\newpage

### Question 7

\newpage

### Question 8

\newpage

## Part 2

### Question 9
